image: python:3.9.9

stages:
  - test

test:
  stage: test
  scripts:
    - python -m venv venv
    - venv/bin/activate
    - python -m pip install -U pip
    - pip install -r requirements.txt
    - pytest
